# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  domain_name: example.com
  secret_key_base: 53d4eb2cfaa4b6df942ad10964173a4feabf39149286fce72a841ac14721e64a0ef0def07b73e6abdba42bed6fa7c20e17d1b9d0bcb9140cc7262729bf279de9

test:
  secret_key_base: 857a19ecad2697a83d3e0f0836ed6bec9167aefc2af99f43d1c8a8702162e774e33096cb7bf4bdc2b41d577c6a0971cedd3c54ec424aedf1470d72f8d45d3027

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
